### ISSUE TITLE
about PCB in utils.py 

### ISSUE THREAD

**Issue by CrapbagMo** [csuhan/VFA#2]
Hi, I appreciate your great work. 
I noticed you have a PCB block in utils.py, I assume it does the same thing as in Defrcn but with CLIP. 
I wonder if your main result on COCO used the refined results and why do you think it is necessary to use a PCB block.

**Comment by CrapbagMo** [comment]
And if you did use clip in your coco result, may i ask what is the result without PCB block?
Thanks

**Comment by csuhan** [comment]
Thanks! 
Our performance on COCO is not so good because it is hard to optimize the VAE on such large datasets: both the input S and output S' of the VAE are changing every iteration.
The pure results are 14.5 (10-shot) and ~18.3 (30-shot). We use PCB to catch up with other methods. You can test VFA w/o PCB by tuning this param off:
https://github.com/csuhan/VFA/blob/e35411eb22b4fc48b524debe58dc7c09be2bf9a6/configs/vfa/coco/vfa_r101_c4_8xb4_coco_10shot-fine-tuning.py#L29

**Comment by CrapbagMo** [comment]
Thanks for your reply!
